services:
  app:
    build:
      context: .
      args:
        VITE_TABLES_APP_URL: "http://localhost:3001" # Or your deployment IP/domain:port
    ports:
      - "3000:3000"
    volumes:
      - data:/app/data
volumes:
  data:
